Vagrant.configure("2") do |config|
    config.vm.define "k8s-centos-master" do |subconfig|
        subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "k8s-centos-master"        
        subconfig.vm.network "private_network", type:"dhcp"
        subconfig.vm.synced_folder ".", "/vagrant", disabled: true                
        subconfig.vm.provision "shell", path: "01-docker.sh"        
        subconfig.vm.provision "shell", path: "02-kubernetes.sh"
        subconfig.vm.provision "shell", path: "03-master-flannel.sh"
        subconfig.vm.provider "hyperv" do |h|            
            h.differencing_disk = true
            h.cpus = 4
            h.memory = 2048
            h.maxmemory = 4096
            h.vmname = "k8s-centos-master"
            h.vlan_id = 7
        end   
    end
    
end
