$VirtualSwitchName = "External"

LINUX_IMAGE = "kmm/ubuntu-xenial64"

Vagrant.configure("2") do |config|
    config.vm.define "builder" do |subconfig|
        subconfig.vm.box = LINUX_IMAGE
        subconfig.vm.hostname = "builder"
        subconfig.vm.network :public_network, bridge: $VirtualSwitchName
        subconfig.vm.synced_folder "../../vagrant-synced/", "/vagrant", type: "smb"
        subconfig.vm.provision "shell", path: "ubuntu.sh"
        subconfig.vm.provision "shell", path: "builder.sh"
        subconfig.vm.provider "hyperv" do |h|
            h.enable_virtualization_extensions = true
            h.differencing_disk = true
            h.cpus = 4
            h.memory = 1024
            h.maxmemory = 4096
            h.vmname = "builder"
        end   
    end    
end
