$VirtualSwitchName = "External"

LINUX_IMAGE = "kmm/ubuntu-xenial64"

Vagrant.configure("2") do |config|
    config.vm.define "k-master" do |subconfig|
        subconfig.vm.box = LINUX_IMAGE
        subconfig.vm.hostname = "k-master"
        subconfig.vm.network :public_network, bridge: $VirtualSwitchName
        subconfig.vm.synced_folder ".", "/vagrant", disabled: true
        subconfig.vm.provision "shell", path: "00-ubuntu.sh"
        subconfig.vm.provision "shell", path: "01-kubernetes.sh"
        subconfig.vm.provision "shell", path: "02-master.sh"
        subconfig.vm.provider "hyperv" do |h|
            h.enable_virtualization_extensions = true
            h.differencing_disk = true
            h.cpus = 4
            h.memory = 2048
            h.maxmemory = 4096
            h.vmname = "k-master"
        end   
    end
    config.vm.define "k-worker-linux" do |subconfig|
        subconfig.vm.box = LINUX_IMAGE
        subconfig.vm.hostname = "k-worker-linux"
        subconfig.vm.network :public_network, bridge: $VirtualSwitchName
        subconfig.vm.synced_folder ".", "/vagrant", disabled: true
        subconfig.vm.provision "shell", path: "00-ubuntu.sh"
        subconfig.vm.provision "shell", path: "01-kubernetes.sh"
        subconfig.vm.provision "shell", path: "02-worker.sh"
        subconfig.vm.provider "hyperv" do |h|
            h.enable_virtualization_extensions = true
            h.differencing_disk = true
            h.cpus = 4
            h.memory = 1024
            h.maxmemory = 4096
            h.vmname = "k-worker-linux"
        end   
    end
    
end
