$VirtualSwitchName = "SA18Lab"

IMAGE = "ws_stack"

Vagrant.configure("2") do |config|
    config.vm.define "k-worker1" do |subconfig|
        subconfig.vm.box = IMAGE
        subconfig.vm.communicator = "winrm"
        subconfig.vm.hostname = "k-worker1"
        subconfig.vm.network :public_network, bridge: $VirtualSwitchName        
        subconfig.vm.provider "hyperv" do |h|
            h.enable_virtualization_extensions = true
            h.differencing_disk = true
            h.cpus = 4
            h.memory = 1024
            h.maxmemory = 4096
            h.vmname = "k-worker1"
            h.vlan_id = 7
        end   
    end
end
